use_frameworks!

platform :ios, '8.0'

target 'SSAddImage_Example' do
  pod 'SSAddImage', :path => '../'

  target 'SSAddImage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
